// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: authors.sql

package dbq

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countAuthors = `-- name: CountAuthors :one
SELECT count(*) FROM authors
WHERE (category_id = $1 OR $1 IS NULL)
  AND (name ILIKE '%' || $2 || '%' OR $2 IS NULL)
`

type CountAuthorsParams struct {
	FilterCategoryID pgtype.UUID `json:"filter_category_id"`
	SearchName       pgtype.Text `json:"search_name"`
}

func (q *Queries) CountAuthors(ctx context.Context, arg CountAuthorsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAuthors, arg.FilterCategoryID, arg.SearchName)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAuthor = `-- name: CreateAuthor :one
INSERT INTO authors (name, bio, born_date, died_date, image_id, category_id)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, name, bio, born_date, died_date, image_id, category_id, created_at, updated_at
`

type CreateAuthorParams struct {
	Name       string      `json:"name"`
	Bio        pgtype.Text `json:"bio"`
	BornDate   pgtype.Date `json:"born_date"`
	DiedDate   pgtype.Date `json:"died_date"`
	ImageID    pgtype.UUID `json:"image_id"`
	CategoryID pgtype.UUID `json:"category_id"`
}

func (q *Queries) CreateAuthor(ctx context.Context, arg CreateAuthorParams) (Author, error) {
	row := q.db.QueryRow(ctx, createAuthor,
		arg.Name,
		arg.Bio,
		arg.BornDate,
		arg.DiedDate,
		arg.ImageID,
		arg.CategoryID,
	)
	var i Author
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Bio,
		&i.BornDate,
		&i.DiedDate,
		&i.ImageID,
		&i.CategoryID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAuthor = `-- name: DeleteAuthor :exec
DELETE FROM authors WHERE id = $1
`

func (q *Queries) DeleteAuthor(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteAuthor, id)
	return err
}

const getAuthor = `-- name: GetAuthor :one
SELECT id, name, bio, born_date, died_date, image_id, category_id, created_at, updated_at
FROM authors WHERE id = $1
`

func (q *Queries) GetAuthor(ctx context.Context, id pgtype.UUID) (Author, error) {
	row := q.db.QueryRow(ctx, getAuthor, id)
	var i Author
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Bio,
		&i.BornDate,
		&i.DiedDate,
		&i.ImageID,
		&i.CategoryID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAuthors = `-- name: ListAuthors :many
SELECT id, name, bio, born_date, died_date, image_id, category_id, created_at, updated_at
FROM authors
WHERE (category_id = $3 OR $3 IS NULL)
  AND (name ILIKE '%' || $4 || '%' OR $4 IS NULL)
ORDER BY name ASC
LIMIT $1 OFFSET $2
`

type ListAuthorsParams struct {
	Limit            int32       `json:"limit"`
	Offset           int32       `json:"offset"`
	FilterCategoryID pgtype.UUID `json:"filter_category_id"`
	SearchName       pgtype.Text `json:"search_name"`
}

func (q *Queries) ListAuthors(ctx context.Context, arg ListAuthorsParams) ([]Author, error) {
	rows, err := q.db.Query(ctx, listAuthors,
		arg.Limit,
		arg.Offset,
		arg.FilterCategoryID,
		arg.SearchName,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Author{}
	for rows.Next() {
		var i Author
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Bio,
			&i.BornDate,
			&i.DiedDate,
			&i.ImageID,
			&i.CategoryID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAuthor = `-- name: UpdateAuthor :one
UPDATE authors
SET name = $1, bio = $2, born_date = $3, died_date = $4,
    image_id = $5, category_id = $6, updated_at = NOW()
WHERE id = $7
RETURNING id, name, bio, born_date, died_date, image_id, category_id, created_at, updated_at
`

type UpdateAuthorParams struct {
	Name       string      `json:"name"`
	Bio        pgtype.Text `json:"bio"`
	BornDate   pgtype.Date `json:"born_date"`
	DiedDate   pgtype.Date `json:"died_date"`
	ImageID    pgtype.UUID `json:"image_id"`
	CategoryID pgtype.UUID `json:"category_id"`
	ID         pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateAuthor(ctx context.Context, arg UpdateAuthorParams) (Author, error) {
	row := q.db.QueryRow(ctx, updateAuthor,
		arg.Name,
		arg.Bio,
		arg.BornDate,
		arg.DiedDate,
		arg.ImageID,
		arg.CategoryID,
		arg.ID,
	)
	var i Author
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Bio,
		&i.BornDate,
		&i.DiedDate,
		&i.ImageID,
		&i.CategoryID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
