// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: images.sql

package dbq

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countImages = `-- name: CountImages :one
SELECT count(*) FROM images
WHERE (category_id = $1 OR $1 IS NULL)
`

func (q *Queries) CountImages(ctx context.Context, filterCategoryID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countImages, filterCategoryID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createImage = `-- name: CreateImage :one
INSERT INTO images (url, alt_text, category_id)
VALUES ($1, $2, $3)
RETURNING id, url, alt_text, category_id, created_at, updated_at
`

type CreateImageParams struct {
	Url        string      `json:"url"`
	AltText    pgtype.Text `json:"alt_text"`
	CategoryID pgtype.UUID `json:"category_id"`
}

func (q *Queries) CreateImage(ctx context.Context, arg CreateImageParams) (Image, error) {
	row := q.db.QueryRow(ctx, createImage, arg.Url, arg.AltText, arg.CategoryID)
	var i Image
	err := row.Scan(
		&i.ID,
		&i.Url,
		&i.AltText,
		&i.CategoryID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteImage = `-- name: DeleteImage :one
DELETE FROM images WHERE id = $1 RETURNING id
`

func (q *Queries) DeleteImage(ctx context.Context, id pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, deleteImage, id)
	err := row.Scan(&id)
	return id, err
}

const getImage = `-- name: GetImage :one
SELECT id, url, alt_text, category_id, created_at, updated_at FROM images WHERE id = $1
`

func (q *Queries) GetImage(ctx context.Context, id pgtype.UUID) (Image, error) {
	row := q.db.QueryRow(ctx, getImage, id)
	var i Image
	err := row.Scan(
		&i.ID,
		&i.Url,
		&i.AltText,
		&i.CategoryID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listImages = `-- name: ListImages :many
SELECT id, url, alt_text, category_id, created_at, updated_at FROM images
WHERE (category_id = $3 OR $3 IS NULL)
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListImagesParams struct {
	Limit            int32       `json:"limit"`
	Offset           int32       `json:"offset"`
	FilterCategoryID pgtype.UUID `json:"filter_category_id"`
}

func (q *Queries) ListImages(ctx context.Context, arg ListImagesParams) ([]Image, error) {
	rows, err := q.db.Query(ctx, listImages, arg.Limit, arg.Offset, arg.FilterCategoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Image{}
	for rows.Next() {
		var i Image
		if err := rows.Scan(
			&i.ID,
			&i.Url,
			&i.AltText,
			&i.CategoryID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateImage = `-- name: UpdateImage :one
UPDATE images
SET url = $1, alt_text = $2, category_id = $3, updated_at = NOW()
WHERE id = $4
RETURNING id, url, alt_text, category_id, created_at, updated_at
`

type UpdateImageParams struct {
	Url        string      `json:"url"`
	AltText    pgtype.Text `json:"alt_text"`
	CategoryID pgtype.UUID `json:"category_id"`
	ID         pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateImage(ctx context.Context, arg UpdateImageParams) (Image, error) {
	row := q.db.QueryRow(ctx, updateImage,
		arg.Url,
		arg.AltText,
		arg.CategoryID,
		arg.ID,
	)
	var i Image
	err := row.Scan(
		&i.ID,
		&i.Url,
		&i.AltText,
		&i.CategoryID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
