// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbq

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Author struct {
	ID         pgtype.UUID        `json:"id"`
	Name       string             `json:"name"`
	Bio        pgtype.Text        `json:"bio"`
	BornDate   pgtype.Date        `json:"born_date"`
	DiedDate   pgtype.Date        `json:"died_date"`
	ImageID    pgtype.UUID        `json:"image_id"`
	CategoryID pgtype.UUID        `json:"category_id"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type Category struct {
	ID        pgtype.UUID        `json:"id"`
	Name      string             `json:"name"`
	Type      string             `json:"type"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Image struct {
	ID         pgtype.UUID        `json:"id"`
	Url        string             `json:"url"`
	AltText    pgtype.Text        `json:"alt_text"`
	CategoryID pgtype.UUID        `json:"category_id"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type Quote struct {
	ID         pgtype.UUID        `json:"id"`
	Title      string             `json:"title"`
	Text       string             `json:"text"`
	AuthorID   pgtype.UUID        `json:"author_id"`
	ImageID    pgtype.UUID        `json:"image_id"`
	CategoryID pgtype.UUID        `json:"category_id"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}
