// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: quotes.sql

package dbq

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countQuotes = `-- name: CountQuotes :one
SELECT count(*) FROM quotes
WHERE (author_id = $1 OR $1 IS NULL)
  AND (category_id = $2 OR $2 IS NULL)
  AND (title ILIKE '%' || $3 || '%' OR $3 IS NULL)
  AND (
    $4::uuid IS NULL
    OR EXISTS (
      SELECT 1 FROM quote_tags qt
      WHERE qt.quote_id = quotes.id
        AND qt.tag_id = $4
    )
  )
`

type CountQuotesParams struct {
	FilterAuthorID   pgtype.UUID `json:"filter_author_id"`
	FilterCategoryID pgtype.UUID `json:"filter_category_id"`
	SearchTitle      pgtype.Text `json:"search_title"`
	FilterTagID      pgtype.UUID `json:"filter_tag_id"`
}

func (q *Queries) CountQuotes(ctx context.Context, arg CountQuotesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countQuotes,
		arg.FilterAuthorID,
		arg.FilterCategoryID,
		arg.SearchTitle,
		arg.FilterTagID,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createQuote = `-- name: CreateQuote :one
INSERT INTO quotes (title, text, author_id, image_id, category_id)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, title, text, author_id, image_id, category_id, created_at, updated_at
`

type CreateQuoteParams struct {
	Title      string      `json:"title"`
	Text       string      `json:"text"`
	AuthorID   pgtype.UUID `json:"author_id"`
	ImageID    pgtype.UUID `json:"image_id"`
	CategoryID pgtype.UUID `json:"category_id"`
}

func (q *Queries) CreateQuote(ctx context.Context, arg CreateQuoteParams) (Quote, error) {
	row := q.db.QueryRow(ctx, createQuote,
		arg.Title,
		arg.Text,
		arg.AuthorID,
		arg.ImageID,
		arg.CategoryID,
	)
	var i Quote
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Text,
		&i.AuthorID,
		&i.ImageID,
		&i.CategoryID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteQuote = `-- name: DeleteQuote :one
DELETE FROM quotes WHERE id = $1 RETURNING id
`

func (q *Queries) DeleteQuote(ctx context.Context, id pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, deleteQuote, id)
	err := row.Scan(&id)
	return id, err
}

const getQuote = `-- name: GetQuote :one
SELECT id, title, text, author_id, image_id, category_id, created_at, updated_at
FROM quotes WHERE id = $1
`

func (q *Queries) GetQuote(ctx context.Context, id pgtype.UUID) (Quote, error) {
	row := q.db.QueryRow(ctx, getQuote, id)
	var i Quote
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Text,
		&i.AuthorID,
		&i.ImageID,
		&i.CategoryID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getQuoteForKeyShare = `-- name: GetQuoteForKeyShare :one
SELECT id FROM quotes WHERE id = $1 FOR KEY SHARE
`

func (q *Queries) GetQuoteForKeyShare(ctx context.Context, id pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getQuoteForKeyShare, id)
	err := row.Scan(&id)
	return id, err
}

const listQuotes = `-- name: ListQuotes :many
SELECT id, title, text, author_id, image_id, category_id, created_at, updated_at
FROM quotes
WHERE (author_id = $3 OR $3 IS NULL)
  AND (category_id = $4 OR $4 IS NULL)
  AND (title ILIKE '%' || $5 || '%' OR $5 IS NULL)
  AND (
    $6::uuid IS NULL
    OR EXISTS (
      SELECT 1 FROM quote_tags qt
      WHERE qt.quote_id = quotes.id
        AND qt.tag_id = $6
    )
  )
ORDER BY created_at DESC, id DESC
LIMIT $1 OFFSET $2
`

type ListQuotesParams struct {
	Limit            int32       `json:"limit"`
	Offset           int32       `json:"offset"`
	FilterAuthorID   pgtype.UUID `json:"filter_author_id"`
	FilterCategoryID pgtype.UUID `json:"filter_category_id"`
	SearchTitle      pgtype.Text `json:"search_title"`
	FilterTagID      pgtype.UUID `json:"filter_tag_id"`
}

func (q *Queries) ListQuotes(ctx context.Context, arg ListQuotesParams) ([]Quote, error) {
	rows, err := q.db.Query(ctx, listQuotes,
		arg.Limit,
		arg.Offset,
		arg.FilterAuthorID,
		arg.FilterCategoryID,
		arg.SearchTitle,
		arg.FilterTagID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Quote{}
	for rows.Next() {
		var i Quote
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Text,
			&i.AuthorID,
			&i.ImageID,
			&i.CategoryID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateQuote = `-- name: UpdateQuote :one
UPDATE quotes
SET title = $1, text = $2, author_id = $3, image_id = $4,
    category_id = $5, updated_at = NOW()
WHERE id = $6
RETURNING id, title, text, author_id, image_id, category_id, created_at, updated_at
`

type UpdateQuoteParams struct {
	Title      string      `json:"title"`
	Text       string      `json:"text"`
	AuthorID   pgtype.UUID `json:"author_id"`
	ImageID    pgtype.UUID `json:"image_id"`
	CategoryID pgtype.UUID `json:"category_id"`
	ID         pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateQuote(ctx context.Context, arg UpdateQuoteParams) (Quote, error) {
	row := q.db.QueryRow(ctx, updateQuote,
		arg.Title,
		arg.Text,
		arg.AuthorID,
		arg.ImageID,
		arg.CategoryID,
		arg.ID,
	)
	var i Quote
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Text,
		&i.AuthorID,
		&i.ImageID,
		&i.CategoryID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
