// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: quotes.sql

package dbq

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countQuotes = `-- name: CountQuotes :one
SELECT count(*) FROM quotes
WHERE (author_id = $1 OR $1 IS NULL)
  AND (category_id = $2 OR $2 IS NULL)
  AND (title ILIKE '%' || $3 || '%' OR $3 IS NULL)
  AND (
    $4::uuid IS NULL
    OR id IN (
      SELECT qt.quote_id FROM quote_tags qt
      WHERE qt.tag_id = $4
    )
  )
  AND (
    $5::text IS NULL
    OR search_vector @@ websearch_to_tsquery('english', $5)
  )
`

type CountQuotesParams struct {
	FilterAuthorID   pgtype.UUID `json:"filter_author_id"`
	FilterCategoryID pgtype.UUID `json:"filter_category_id"`
	SearchTitle      pgtype.Text `json:"search_title"`
	FilterTagID      pgtype.UUID `json:"filter_tag_id"`
	SearchQ          pgtype.Text `json:"search_q"`
}

// Mirrors the WHERE shape used in ListQuotes so the same plans fire. Keeping
// the two clauses byte-identical (modulo SELECT vs count and the ORDER BY +
// LIMIT that count doesn't need) prevents pagination totals from drifting
// from the returned items if the filter shape ever changes again.
func (q *Queries) CountQuotes(ctx context.Context, arg CountQuotesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countQuotes,
		arg.FilterAuthorID,
		arg.FilterCategoryID,
		arg.SearchTitle,
		arg.FilterTagID,
		arg.SearchQ,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createQuote = `-- name: CreateQuote :one
INSERT INTO quotes (title, text, author_id, image_id, category_id)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, title, text, author_id, image_id, category_id, created_at, updated_at, search_vector
`

type CreateQuoteParams struct {
	Title      string      `json:"title"`
	Text       string      `json:"text"`
	AuthorID   pgtype.UUID `json:"author_id"`
	ImageID    pgtype.UUID `json:"image_id"`
	CategoryID pgtype.UUID `json:"category_id"`
}

func (q *Queries) CreateQuote(ctx context.Context, arg CreateQuoteParams) (Quote, error) {
	row := q.db.QueryRow(ctx, createQuote,
		arg.Title,
		arg.Text,
		arg.AuthorID,
		arg.ImageID,
		arg.CategoryID,
	)
	var i Quote
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Text,
		&i.AuthorID,
		&i.ImageID,
		&i.CategoryID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SearchVector,
	)
	return i, err
}

const deleteQuote = `-- name: DeleteQuote :one
DELETE FROM quotes WHERE id = $1 RETURNING id
`

func (q *Queries) DeleteQuote(ctx context.Context, id pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, deleteQuote, id)
	err := row.Scan(&id)
	return id, err
}

const getQuote = `-- name: GetQuote :one
SELECT id, title, text, author_id, image_id, category_id, created_at, updated_at, search_vector
FROM quotes WHERE id = $1
`

func (q *Queries) GetQuote(ctx context.Context, id pgtype.UUID) (Quote, error) {
	row := q.db.QueryRow(ctx, getQuote, id)
	var i Quote
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Text,
		&i.AuthorID,
		&i.ImageID,
		&i.CategoryID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SearchVector,
	)
	return i, err
}

const getQuoteForKeyShare = `-- name: GetQuoteForKeyShare :one
SELECT id FROM quotes WHERE id = $1 FOR KEY SHARE
`

func (q *Queries) GetQuoteForKeyShare(ctx context.Context, id pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getQuoteForKeyShare, id)
	err := row.Scan(&id)
	return id, err
}

const listQuotes = `-- name: ListQuotes :many
SELECT id, title, text, author_id, image_id, category_id, created_at, updated_at, search_vector
FROM quotes
WHERE (author_id = $3 OR $3 IS NULL)
  AND (category_id = $4 OR $4 IS NULL)
  AND (title ILIKE '%' || $5 || '%' OR $5 IS NULL)
  AND (
    $6::uuid IS NULL
    OR id IN (
      SELECT qt.quote_id FROM quote_tags qt
      WHERE qt.tag_id = $6
    )
  )
  AND (
    $7::text IS NULL
    OR search_vector @@ websearch_to_tsquery('english', $7)
  )
ORDER BY
  CASE
    WHEN $7::text IS NULL THEN NULL
    ELSE ts_rank_cd(search_vector, websearch_to_tsquery('english', $7))
  END DESC NULLS LAST,
  created_at DESC, id DESC
LIMIT $1 OFFSET $2
`

type ListQuotesParams struct {
	Limit            int32       `json:"limit"`
	Offset           int32       `json:"offset"`
	FilterAuthorID   pgtype.UUID `json:"filter_author_id"`
	FilterCategoryID pgtype.UUID `json:"filter_category_id"`
	SearchTitle      pgtype.Text `json:"search_title"`
	FilterTagID      pgtype.UUID `json:"filter_tag_id"`
	SearchQ          pgtype.Text `json:"search_q"`
}

// The tag filter is expressed as `id IN (SELECT ...)` rather than a correlated
// EXISTS so PostgreSQL can hash the inner result once and run it as a hashed
// semi-join driven from ix_quote_tags_tag_id. With a correlated EXISTS the
// planner re-probes quote_tags_pkey per outer row (~100K loops, ~300K buffers
// on a 100K-quote dataset for a sparse tag); the IN form drops to ~1.2K
// buffers regardless of tag selectivity. See PR #14 EXPLAIN ANALYZE evidence.
//
// The search_q filter runs a websearch_to_tsquery('english', ...) against the
// quotes.search_vector GIN index (added in migration 000007). websearch_to_tsquery
// is used deliberately over plainto_tsquery / to_tsquery: it accepts the
// user-facing search-box syntax ("exact phrase", -excluded, or) and never
// raises SQLSTATE 42601 on stray punctuation, so any string typed by a user is
// a valid input. When search_q is NULL, the clause short-circuits and the
// tsquery expression is never evaluated — the planner reduces it to a
// constant-false OR constant-true and prunes the @@ branch entirely.
//
// When search_q is set the ORDER BY switches to ts_rank_cd DESC first, falling
// back to (created_at DESC, id DESC) for tie-breaking and for the
// deterministic-pagination rule in 12-pr-review-lessons.mdc §Indexing. When
// search_q is NULL the CASE returns NULL uniformly and the secondary keys take
// over, so the historic ordering is preserved bit-for-bit.
//
// search_vector is included in the returned columns so sqlc keeps emitting
// the canonical `Quote` row type (rather than per-query ListQuotesRow etc.).
// The value is never consumed in Go; see the sqlc.yaml override mapping
// tsvector -> string.
func (q *Queries) ListQuotes(ctx context.Context, arg ListQuotesParams) ([]Quote, error) {
	rows, err := q.db.Query(ctx, listQuotes,
		arg.Limit,
		arg.Offset,
		arg.FilterAuthorID,
		arg.FilterCategoryID,
		arg.SearchTitle,
		arg.FilterTagID,
		arg.SearchQ,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Quote{}
	for rows.Next() {
		var i Quote
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Text,
			&i.AuthorID,
			&i.ImageID,
			&i.CategoryID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SearchVector,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateQuote = `-- name: UpdateQuote :one
UPDATE quotes
SET title = $1, text = $2, author_id = $3, image_id = $4,
    category_id = $5, updated_at = NOW()
WHERE id = $6
RETURNING id, title, text, author_id, image_id, category_id, created_at, updated_at, search_vector
`

type UpdateQuoteParams struct {
	Title      string      `json:"title"`
	Text       string      `json:"text"`
	AuthorID   pgtype.UUID `json:"author_id"`
	ImageID    pgtype.UUID `json:"image_id"`
	CategoryID pgtype.UUID `json:"category_id"`
	ID         pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateQuote(ctx context.Context, arg UpdateQuoteParams) (Quote, error) {
	row := q.db.QueryRow(ctx, updateQuote,
		arg.Title,
		arg.Text,
		arg.AuthorID,
		arg.ImageID,
		arg.CategoryID,
		arg.ID,
	)
	var i Quote
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Text,
		&i.AuthorID,
		&i.ImageID,
		&i.CategoryID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SearchVector,
	)
	return i, err
}
