// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: quote_tags.sql

package dbq

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addTagToQuote = `-- name: AddTagToQuote :exec
INSERT INTO quote_tags (quote_id, tag_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddTagToQuoteParams struct {
	QuoteID pgtype.UUID `json:"quote_id"`
	TagID   pgtype.UUID `json:"tag_id"`
}

func (q *Queries) AddTagToQuote(ctx context.Context, arg AddTagToQuoteParams) error {
	_, err := q.db.Exec(ctx, addTagToQuote, arg.QuoteID, arg.TagID)
	return err
}

const countQuotesByTag = `-- name: CountQuotesByTag :one
SELECT count(*)
FROM quote_tags
WHERE tag_id = $1
`

func (q *Queries) CountQuotesByTag(ctx context.Context, tagID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countQuotesByTag, tagID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listQuotesByTag = `-- name: ListQuotesByTag :many
SELECT q.id, q.title, q.text, q.author_id, q.image_id, q.category_id, q.created_at, q.updated_at
FROM quotes q
JOIN quote_tags qt ON qt.quote_id = q.id
WHERE qt.tag_id = $1
ORDER BY q.created_at DESC, q.id DESC
LIMIT $2 OFFSET $3
`

type ListQuotesByTagParams struct {
	TagID  pgtype.UUID `json:"tag_id"`
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
}

func (q *Queries) ListQuotesByTag(ctx context.Context, arg ListQuotesByTagParams) ([]Quote, error) {
	rows, err := q.db.Query(ctx, listQuotesByTag, arg.TagID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Quote{}
	for rows.Next() {
		var i Quote
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Text,
			&i.AuthorID,
			&i.ImageID,
			&i.CategoryID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTagsByQuote = `-- name: ListTagsByQuote :many
SELECT t.id, t.name, t.created_at
FROM tags t
JOIN quote_tags qt ON qt.tag_id = t.id
WHERE qt.quote_id = $1
ORDER BY t.name
`

func (q *Queries) ListTagsByQuote(ctx context.Context, quoteID pgtype.UUID) ([]Tag, error) {
	rows, err := q.db.Query(ctx, listTagsByQuote, quoteID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Tag{}
	for rows.Next() {
		var i Tag
		if err := rows.Scan(&i.ID, &i.Name, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeTagFromQuote = `-- name: RemoveTagFromQuote :exec
DELETE FROM quote_tags
WHERE quote_id = $1 AND tag_id = $2
`

type RemoveTagFromQuoteParams struct {
	QuoteID pgtype.UUID `json:"quote_id"`
	TagID   pgtype.UUID `json:"tag_id"`
}

func (q *Queries) RemoveTagFromQuote(ctx context.Context, arg RemoveTagFromQuoteParams) error {
	_, err := q.db.Exec(ctx, removeTagFromQuote, arg.QuoteID, arg.TagID)
	return err
}

